[package]
name = "python-oxidized-importer"
version = "0.3.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "Python-2.0 OR MPL-2.0"
description = "A Rust-powered Python importer"
readme = "README.md"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
memmap = "0.7"
once_cell = "1.7"

[dependencies.python-packed-resources]
version = "0.8.0-pre"
path = "../python-packed-resources"

[dependencies.python-packaging]
version = "0.11.0-pre"
path = "../python-packaging"
default-features = false

[dependencies.pyo3]
version = "0.14.5"
features = ["macros"]

[dependencies.tugger-file-manifest]
version = "0.6.0-pre"
path = "../tugger-file-manifest"

[dependencies.zip]
version = "0.5"
optional = true
default-features = false
features = ["deflate"]

[target.'cfg(windows)'.dependencies]
memory-module-sys = "0.3"
winapi = { version = "0.3", features = ["libloaderapi", "memoryapi", "minwindef"] }

[features]
default = ["zipimport"]

# Build the crate in Python extension module mode. This will make linking
# correct so the resulting library can be loaded as a Python extension
# module.
extension-module = ["pyo3/extension-module"]

# Enable support for importing from zip files.
zipimport = ["zip"]
